name: CyanogenMod CI

on:
  workflow_dispatch:
jobs:
  build:
    name: CyanogenMod Build CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - name: Check Out
      uses: actions/checkout@v3
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
    - name: Installing JDK 7 + Build Dependencies
      run: |
        sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu trusty main restricted universe multiverse"
        sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu trusty-security main restricted universe multiverse"
        sudo apt-get update
        sudo apt-get install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32z1-dev liblz4-tool libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev axel python openjdk-7-jdk
    - name: Syncing CyanogenMod sources
      run: |
        mkdir ~/TWRP
        cd ~/TWRP
        mkdir ~/.bin
        curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        python3 ~/.bin/repo init --depth=1 -u https://github.com/CyanogenMod/android.git -b cm-12.1
        git clone https://github.com/unlegacy-devices/android_device_samsung_loganreltexx -b cm-12.1 ~/TWRP/device/samsung/loganreltexx
        git clone https://github.com/kotzir/proprietary_vendor_samsung_loganreltexx -b cm-12.1 ~/TWRP/vendor/samsung/loganreltexx
        git clone https://github.com/kotzir/android_kernel_samsung_msm8930-common -b cm-12.1 ~/TWRP/kernel/samsung/msm8930-common
        python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
    - name: Building CyanogenMod
      run: |
        OLDPATH=$PATH
        OLDJAVAHOME=$JAVA_HOME
        export PATH="$HOME/.jdk_7/java-se-7u75-ri/bin:$PATH"
        export JAVA_HOME="$HOME/.jdk_7/java-se-7u75-ri"
        cd ~/TWRP
        git clone https://github.com/kotzir/android_device_samsung_qcom-common -b cm-12.1 ~/TWRP/device/samsung/qcom-common
        git clone https://github.com/kotzir/android_device_samsung_msm8930-common -b cm-12.1 ~/TWRP/device/samsung/msm8930-common
        git clone https://github.com/CyanogenMod/android_hardware_samsung -b cm-12.1 ~/TWRP/hardware/samsung
        git clone https://github.com/CyanogenMod/android_device_qcom_common -b cm-12.1 ~/TWRP/device/qcom/common
        git clone https://github.com/CyanogenMod/android_hardware_qcom_fm -b cm-14.1 ~/TWRP/hardware/qcom/fm
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        lunch cm_loganreltexx-eng
        make -j$(nproc --all) otapackage
        export PATH=$OLDPATH
        export JAVA_HOME=$OLDJAVAHOME
    - name: CD to CyanogenMod builds
      run: |
         cd $OUT
         ls
    - name: Uploading CyanogenMod builds
      uses: actions/upload-artifact@v2
      with:
        name: cm
        path: /home/runner/TWRP/out/target/product/loganreltexx/*.zip
    - name: Uploading LineageOS Recovery builds
      uses: actions/upload-artifact@v2
      with:
        name: cmrecovery
        path: /home/runner/TWRP/out/target/product/loganreltexx/recovery.*
